name: whastapp
description: Projeto Flutter modernizado com estrutura modular.
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - imagens/logo.png
    - imagens/usuario.png
    - imagens/bg.png
